name: power_logger
description: A well log tool on flutter, support Dio and custom type data.
version: 1.1.0
homepage: https://github.com/laiiihz/power_logger

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_highlight: ^0.7.0
  device_info: ^2.0.0
  package_info: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  logger: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
